export type Difficulty = "fácil" | "médio" | "difícil";

export type Step = {
  id: string;
  order: number;
  title: string;
  goal: string;
  eta: string;
  difficulty: Difficulty;
  impact: string;
  incomeAfter: number;
  skills: string[];
  projects: string[];
  resources: { label: string; type: string }[];
  checklist: { id: string; label: string; done: boolean }[];
  xp: number;
  status: "concluído" | "em andamento" | "bloqueado";
};

export const user = {
  name: "Arthur Streck",
  firstName: "Arthur",
  initials: "AS",
  role: "Auxiliar administrativo",
  target: "Desenvolvedor back-end",
  currentIncome: 2600,
  goalIncome: 8000,
  level: 4,
  levelName: "Construtor",
  xp: 2380,
  xpToNext: 3200,
  streak: 12,
  hoursPerWeek: 12,
  deadlineMonths: 10,
  goalType: "Emprego CLT ou remoto",
};

export const steps: Step[] = [
  {
    id: "s1",
    order: 1,
    title: "Fundamentos de Python",
    goal: "Escrever scripts com lógica, funções e estruturas de dados sem consultar tutorial.",
    eta: "3 semanas",
    difficulty: "fácil",
    impact: "Base obrigatória para todo o resto da rota",
    incomeAfter: 2600,
    skills: ["Python", "Lógica", "Git básico"],
    projects: ["Organizador de arquivos por CLI"],
    resources: [
      { label: "Python do zero — trilha guiada", type: "Trilha" },
      { label: "50 exercícios de lógica", type: "Prática" },
    ],
    checklist: [
      { id: "c1", label: "Sintaxe e tipos", done: true },
      { id: "c2", label: "Funções e módulos", done: true },
      { id: "c3", label: "Primeiro script útil", done: true },
    ],
    xp: 320,
    status: "concluído",
  },
  {
    id: "s2",
    order: 2,
    title: "APIs com FastAPI",
    goal: "Construir e documentar uma API REST com autenticação simples.",
    eta: "4 semanas",
    difficulty: "médio",
    impact: "Primeira habilidade diretamente pedida em vagas júnior",
    incomeAfter: 3400,
    skills: ["FastAPI", "REST", "HTTP", "Pydantic"],
    projects: ["API de finanças pessoais"],
    resources: [
      { label: "APIs na prática", type: "Trilha" },
      { label: "Documentação FastAPI", type: "Doc" },
    ],
    checklist: [
      { id: "c1", label: "Rotas e verbos", done: true },
      { id: "c2", label: "Validação de dados", done: true },
      { id: "c3", label: "Autenticação por token", done: false },
      { id: "c4", label: "Deploy da API", done: false },
    ],
    xp: 480,
    status: "em andamento",
  },
  {
    id: "s3",
    order: 3,
    title: "Projeto real publicado no GitHub",
    goal: "Ter um repositório com README, testes e demo funcionando online.",
    eta: "2 semanas",
    difficulty: "médio",
    impact: "Prova concreta de capacidade — dobra respostas de recrutadores",
    incomeAfter: 3400,
    skills: ["Git avançado", "README", "Testes"],
    projects: ["Refatorar API de finanças em projeto vitrine"],
    resources: [{ label: "Anatomia de um repositório contratável", type: "Guia" }],
    checklist: [
      { id: "c1", label: "README com prints", done: false },
      { id: "c2", label: "Testes automatizados", done: false },
      { id: "c3", label: "Deploy público", done: false },
    ],
    xp: 400,
    status: "bloqueado",
  },
  {
    id: "s4",
    order: 4,
    title: "Bancos de dados e SQL",
    goal: "Modelar dados relacionais e escrever consultas com joins e índices.",
    eta: "4 semanas",
    difficulty: "médio",
    impact: "Requisito em 9 de cada 10 vagas back-end",
    incomeAfter: 4200,
    skills: ["PostgreSQL", "SQL", "Modelagem"],
    projects: ["Migrar projeto para Postgres"],
    resources: [{ label: "SQL para desenvolvedores", type: "Trilha" }],
    checklist: [
      { id: "c1", label: "Modelagem relacional", done: false },
      { id: "c2", label: "Joins e agregações", done: false },
      { id: "c3", label: "Índices e performance", done: false },
    ],
    xp: 520,
    status: "bloqueado",
  },
  {
    id: "s5",
    order: 5,
    title: "Primeiros freelas",
    goal: "Fechar 2 trabalhos pequenos pagos para gerar renda e repertório.",
    eta: "6 semanas",
    difficulty: "médio",
    impact: "+R$ 900/mês em média já no curto prazo",
    incomeAfter: 5100,
    skills: ["Proposta comercial", "Escopo", "Entrega"],
    projects: ["Automação para pequeno negócio"],
    resources: [{ label: "Como precificar seu primeiro freela", type: "Guia" }],
    checklist: [
      { id: "c1", label: "Perfil em 2 plataformas", done: false },
      { id: "c2", label: "10 propostas enviadas", done: false },
      { id: "c3", label: "Primeiro projeto entregue", done: false },
    ],
    xp: 600,
    status: "bloqueado",
  },
  {
    id: "s6",
    order: 6,
    title: "Projeto avançado + Docker",
    goal: "Aplicação com filas, testes e ambiente conteinerizado.",
    eta: "6 semanas",
    difficulty: "difícil",
    impact: "Sai do nível júnior raso e entra em processos melhores",
    incomeAfter: 6000,
    skills: ["Docker", "Filas", "CI/CD"],
    projects: ["Plataforma de agendamentos multiusuário"],
    resources: [{ label: "Docker essencial", type: "Trilha" }],
    checklist: [
      { id: "c1", label: "Containerizar aplicação", done: false },
      { id: "c2", label: "Pipeline de CI", done: false },
    ],
    xp: 720,
    status: "bloqueado",
  },
  {
    id: "s7",
    order: 7,
    title: "Currículo e presença profissional",
    goal: "Currículo de 1 página e LinkedIn alinhados à vaga alvo.",
    eta: "1 semana",
    difficulty: "fácil",
    impact: "Aumenta taxa de resposta antes mesmo de novas skills",
    incomeAfter: 6000,
    skills: ["Comunicação", "Posicionamento"],
    projects: ["Portfólio em uma página"],
    resources: [{ label: "Currículo para dev sem experiência", type: "Guia" }],
    checklist: [
      { id: "c1", label: "Currículo revisado", done: false },
      { id: "c2", label: "LinkedIn otimizado", done: false },
    ],
    xp: 260,
    status: "bloqueado",
  },
  {
    id: "s8",
    order: 8,
    title: "Candidaturas direcionadas",
    goal: "40 candidaturas em vagas compatíveis com a rota concluída.",
    eta: "5 semanas",
    difficulty: "médio",
    impact: "Etapa que converte aprendizado em salário",
    incomeAfter: 7000,
    skills: ["Entrevista técnica", "Negociação"],
    projects: ["Simulações de entrevista"],
    resources: [{ label: "Roteiro de entrevista técnica", type: "Guia" }],
    checklist: [
      { id: "c1", label: "Lista de 40 empresas", done: false },
      { id: "c2", label: "Simulados técnicos", done: false },
    ],
    xp: 640,
    status: "bloqueado",
  },
  {
    id: "s9",
    order: 9,
    title: "Especialização em dados ou cloud",
    goal: "Escolher uma trilha de especialização e chegar a nível pleno.",
    eta: "10 semanas",
    difficulty: "difícil",
    impact: "Faixa de R$ 8.000+ em vagas remotas",
    incomeAfter: 8000,
    skills: ["AWS", "Pipelines", "Arquitetura"],
    projects: ["Pipeline de dados em nuvem"],
    resources: [{ label: "Cloud para back-end", type: "Trilha" }],
    checklist: [{ id: "c1", label: "Definir especialização", done: false }],
    xp: 900,
    status: "bloqueado",
  },
];

export const skills = [
  { name: "Python", level: 72, category: "Linguagem", demand: "Altíssima" },
  { name: "FastAPI", level: 48, category: "Framework", demand: "Alta" },
  { name: "Git", level: 65, category: "Ferramenta", demand: "Altíssima" },
  { name: "SQL", level: 22, category: "Dados", demand: "Altíssima" },
  { name: "Docker", level: 8, category: "Infra", demand: "Alta" },
  { name: "Testes", level: 15, category: "Qualidade", demand: "Média" },
  { name: "Comunicação", level: 80, category: "Humana", demand: "Alta" },
  { name: "AWS", level: 0, category: "Cloud", demand: "Alta" },
];

export const projects = [
  {
    id: "p1",
    title: "API de finanças pessoais",
    status: "Em andamento",
    progress: 55,
    impact: "Alto",
    stack: ["Python", "FastAPI"],
    summary: "CRUD de lançamentos, relatórios mensais e autenticação por token.",
    weeks: 3,
  },
  {
    id: "p2",
    title: "Organizador de arquivos CLI",
    status: "Concluído",
    progress: 100,
    impact: "Médio",
    stack: ["Python"],
    summary: "Script que classifica arquivos por tipo e data com logs.",
    weeks: 1,
  },
  {
    id: "p3",
    title: "Plataforma de agendamentos",
    status: "Sugerido",
    progress: 0,
    impact: "Muito alto",
    stack: ["FastAPI", "Postgres", "Docker"],
    summary: "Multiusuário com filas de notificação — projeto vitrine do portfólio.",
    weeks: 6,
  },
  {
    id: "p4",
    title: "Automação para comércio local",
    status: "Sugerido",
    progress: 0,
    impact: "Alto",
    stack: ["Python", "Sheets API"],
    summary: "Primeiro freela realista, escopo pequeno e entrega em 10 dias.",
    weeks: 2,
  },
];

export const opportunities = [
  {
    id: "o1",
    title: "Desenvolvedor Back-end Júnior",
    company: "Cortex Labs",
    mode: "Remoto",
    salary: "R$ 5.500 – 7.000",
    match: 78,
    missing: ["SQL avançado", "Docker"],
    type: "CLT",
  },
  {
    id: "o2",
    title: "Estágio em Engenharia de Dados",
    company: "Nuvem9",
    mode: "Híbrido",
    salary: "R$ 2.800",
    match: 91,
    missing: ["SQL básico"],
    type: "Estágio",
  },
  {
    id: "o3",
    title: "Automação de processos (projeto)",
    company: "Freela — Marketplace",
    mode: "Remoto",
    salary: "R$ 1.400 / projeto",
    match: 84,
    missing: [],
    type: "Freelancer",
  },
  {
    id: "o4",
    title: "Desenvolvedor Python Pleno",
    company: "Órbita Tech",
    mode: "Remoto",
    salary: "R$ 8.000 – 10.500",
    match: 41,
    missing: ["AWS", "Arquitetura", "Testes"],
    type: "CLT",
  },
];

export const activity = [
  { label: "Concluiu “Validação de dados”", when: "hoje", xp: 60 },
  { label: "Sequência de 12 dias mantida", when: "hoje", xp: 25 },
  { label: "Projeto API de finanças chegou a 55%", when: "ontem", xp: 90 },
  { label: "Etapa 1 finalizada: Fundamentos de Python", when: "3 dias", xp: 320 },
];

export const incomeCurve = [2600, 2600, 3400, 3400, 4200, 5100, 6000, 7000, 8000];

export const onboardingQuestions = [
  {
    key: "renda",
    title: "Quanto você ganha hoje?",
    hint: "Sem julgamento. É só o ponto de partida da sua rota.",
    kind: "money" as const,
    placeholder: "R$ 2.600",
  },
  {
    key: "meta",
    title: "Quanto você quer ganhar?",
    hint: "Pense em um número que mudaria sua vida nos próximos meses.",
    kind: "money" as const,
    placeholder: "R$ 8.000",
  },
  {
    key: "profissao",
    title: "O que você faz atualmente?",
    hint: "Profissão, cargo ou “estudando”.",
    kind: "text" as const,
    placeholder: "Auxiliar administrativo",
  },
  {
    key: "experiencia",
    title: "Qual seu nível de experiência?",
    hint: "Considere qualquer experiência com tecnologia.",
    kind: "options" as const,
    options: ["Nenhuma", "Iniciante", "Intermediária", "Avançada"],
  },
  {
    key: "escolaridade",
    title: "Qual sua escolaridade?",
    hint: "Isso ajuda a filtrar oportunidades reais.",
    kind: "options" as const,
    options: ["Ensino médio", "Técnico", "Cursando superior", "Superior completo"],
  },
  {
    key: "skills",
    title: "O que você já sabe fazer?",
    hint: "Selecione tudo que se aplica.",
    kind: "multi" as const,
    options: [
      "Excel",
      "Python",
      "JavaScript",
      "Design",
      "Vendas",
      "Atendimento",
      "SQL",
      "Inglês",
      "Marketing",
      "Escrita",
    ],
  },
  {
    key: "area",
    title: "Onde você gostaria de trabalhar?",
    hint: "Escolha a área que mais te atrai.",
    kind: "options" as const,
    options: ["Programação", "Dados", "Design", "Produto", "Marketing", "Infra / Cloud"],
  },
  {
    key: "horas",
    title: "Quantas horas livres por semana?",
    hint: "Sua rota se adapta ao tempo que você realmente tem.",
    kind: "options" as const,
    options: ["Até 5h", "5 a 10h", "10 a 20h", "Mais de 20h"],
  },
  {
    key: "objetivo",
    title: "O que você quer conquistar?",
    hint: "Podemos ajustar depois.",
    kind: "options" as const,
    options: ["Emprego", "Estágio", "Freelancer", "Trabalho remoto", "Empreender"],
  },
  {
    key: "prazo",
    title: "Em quanto tempo?",
    hint: "Prazos curtos geram rotas mais intensas.",
    kind: "options" as const,
    options: ["3 meses", "6 meses", "10 meses", "1 ano ou mais"],
  },
];
