import type { AreaId, ExperienceId, OnboardingProfile } from "@/lib/onboarding";
import { horizons } from "@/lib/onboarding";
import type { Difficulty } from "@/lib/mock";
import type { RouteStep } from "@/lib/route-map";

/**
 * Motor de geração de rota baseado em regras — não é IA, é determinístico e auditável.
 *
 * Cada template cobre uma área de destino (`AreaId`) com uma sequência real de etapas. Isso
 * resolve o maior problema do produto antes desta mudança: TODO usuário via a mesma rota fixa
 * ("Arthur Streck", Python → FastAPI) não importa o que respondesse no onboarding. Agora a
 * área escolhida decide o conteúdo, a renda projetada escala entre a renda atual e a meta reais
 * do usuário, e o ritmo (semana de início de cada etapa) escala com as horas/semana informadas.
 *
 * Cobertura: tech, data, design e marketing têm conteúdo dedicado, e "ai" reaproveita o template
 * de tech (a base — lógica, Python, APIs, dados — é a mesma). As demais áreas (sales, finance,
 * engineering, admin, audiovisual, other) caem no template "generic" — habilidades digitais
 * amplamente aplicáveis. Não é personalização completa, mas nenhuma área fica com conteúdo de
 * outra que não faz sentido (ex.: alguém de Vendas nunca vê "Aprenda FastAPI").
 */

type TemplateStep = {
  id: string;
  title: string;
  goal: string;
  difficulty: Difficulty;
  impact: string;
  skills: string[];
  projects: string[];
  resources: { label: string; type: string }[];
  checklist: string[];
  xp: number;
  why: string;
  impactLevel: "médio" | "alto" | "muito alto";
  milestone: string;
  demandPct: number;
  /** horas de estudo estimadas para esta etapa especificamente */
  hours: number;
  /** 0 a 1: posição da renda projetada desta etapa entre a renda atual e a meta */
  incomeWeight: number;
};

const TECH: TemplateStep[] = [
  {
    id: "step-1",
    title: "Fundamentos de programação",
    goal: "Escrever scripts com lógica, funções e estruturas de dados sem consultar tutorial.",
    difficulty: "fácil",
    impact: "Base obrigatória para todo o resto da rota",
    skills: ["Python", "Lógica", "Git básico"],
    projects: ["Organizador de arquivos por CLI"],
    resources: [
      { label: "Python do zero — trilha guiada", type: "Trilha" },
      { label: "50 exercícios de lógica", type: "Prática" },
    ],
    checklist: ["Sintaxe e tipos", "Funções e módulos", "Primeiro script útil"],
    xp: 320,
    why: "Sem lógica e sintaxe sólidas todo o resto da rota vira decoreba. É aqui que você deixa de copiar tutorial e começa a resolver problema.",
    impactLevel: "alto",
    milestone: "Primeiro código próprio funcionando",
    demandPct: 96,
    hours: 36,
    incomeWeight: 0,
  },
  {
    id: "step-2",
    title: "APIs e back-end",
    goal: "Construir e documentar uma API REST com autenticação simples.",
    difficulty: "médio",
    impact: "Primeira habilidade diretamente pedida em vagas júnior",
    skills: ["FastAPI", "REST", "HTTP"],
    projects: ["API de finanças pessoais"],
    resources: [
      { label: "APIs na prática", type: "Trilha" },
      { label: "Documentação FastAPI", type: "Doc" },
    ],
    checklist: ["Rotas e verbos", "Validação de dados", "Autenticação por token", "Deploy da API"],
    xp: 480,
    why: "APIs são o coração do trabalho back-end. É a primeira habilidade que aparece literalmente escrita nas vagas júnior que você quer.",
    impactLevel: "muito alto",
    milestone: "Pronto para vagas de estágio/júnior back-end",
    demandPct: 87,
    hours: 48,
    incomeWeight: 0.15,
  },
  {
    id: "step-3",
    title: "Projeto real publicado",
    goal: "Ter um repositório com README, testes e demo funcionando online.",
    difficulty: "médio",
    impact: "Prova concreta de capacidade — dobra respostas de recrutadores",
    skills: ["Git avançado", "README", "Testes"],
    projects: ["Refatorar API em projeto vitrine"],
    resources: [{ label: "Anatomia de um repositório contratável", type: "Guia" }],
    checklist: ["README com prints", "Testes automatizados", "Deploy público"],
    xp: 400,
    why: "Recrutador não lê promessa, lê repositório. Um projeto público bem apresentado é o que transforma estudo em prova.",
    impactLevel: "muito alto",
    milestone: "Portfólio com prova real de entrega",
    demandPct: 74,
    hours: 24,
    incomeWeight: 0.3,
  },
  {
    id: "step-4",
    title: "Bancos de dados e SQL",
    goal: "Modelar dados relacionais e escrever consultas com joins e índices.",
    difficulty: "médio",
    impact: "Requisito em 9 de cada 10 vagas back-end",
    skills: ["PostgreSQL", "SQL", "Modelagem"],
    projects: ["Migrar projeto para Postgres"],
    resources: [{ label: "SQL para desenvolvedores", type: "Trilha" }],
    checklist: ["Modelagem relacional", "Joins e agregações", "Índices e performance"],
    xp: 520,
    why: "Toda aplicação real guarda dados. Sem SQL você é barrado no teste técnico mesmo sabendo programar.",
    impactLevel: "muito alto",
    milestone: "Aprovação em testes técnicos de dados",
    demandPct: 91,
    hours: 44,
    incomeWeight: 0.42,
  },
  {
    id: "step-5",
    title: "Primeiros freelas",
    goal: "Fechar trabalhos pequenos pagos para gerar renda e repertório real.",
    difficulty: "médio",
    impact: "Renda extra já no curto prazo, sem esperar a vaga CLT",
    skills: ["Proposta comercial", "Escopo", "Entrega"],
    projects: ["Automação para pequeno negócio"],
    resources: [{ label: "Como precificar seu primeiro freela", type: "Guia" }],
    checklist: ["Perfil em 2 plataformas", "10 propostas enviadas", "Primeiro projeto entregue"],
    xp: 600,
    why: "Freela paga a conta enquanto você estuda e gera repertório de cliente real — dois coelhos com o mesmo tiro.",
    impactLevel: "alto",
    milestone: "Primeira renda extra com tecnologia",
    demandPct: 41,
    hours: 60,
    incomeWeight: 0.58,
  },
  {
    id: "step-6",
    title: "Projeto avançado + Docker",
    goal: "Aplicação com filas, testes e ambiente conteinerizado.",
    difficulty: "difícil",
    impact: "Sai do nível júnior raso e entra em processos melhores",
    skills: ["Docker", "Filas", "CI/CD"],
    projects: ["Plataforma multiusuário com notificações"],
    resources: [{ label: "Docker essencial", type: "Trilha" }],
    checklist: ["Containerizar aplicação", "Pipeline de CI"],
    xp: 720,
    why: "Docker e CI separam quem fez curso de quem trabalha em produção. É o salto do júnior raso para o júnior disputado.",
    impactLevel: "alto",
    milestone: "Perfil competitivo para pleno em 12 meses",
    demandPct: 68,
    hours: 56,
    incomeWeight: 0.75,
  },
  {
    id: "step-7",
    title: "Candidaturas direcionadas",
    goal: "Currículo, LinkedIn e uma lista qualificada de vagas compatíveis.",
    difficulty: "médio",
    impact: "Etapa que converte aprendizado em salário",
    skills: ["Entrevista técnica", "Posicionamento"],
    projects: ["Simulações de entrevista"],
    resources: [{ label: "Roteiro de entrevista técnica", type: "Guia" }],
    checklist: ["Currículo revisado", "LinkedIn otimizado", "Lista de empresas-alvo"],
    xp: 640,
    why: "Candidatura é funil: volume qualificado com repertório técnico é o que fecha a diferença até a sua meta de renda.",
    impactLevel: "muito alto",
    milestone: "Primeira oferta formal na área",
    demandPct: 100,
    hours: 30,
    incomeWeight: 1,
  },
];

const DATA: TemplateStep[] = [
  {
    id: "step-1",
    title: "Fundamentos de Excel e lógica de dados",
    goal: "Organizar, limpar e cruzar planilhas sem depender de fórmula pronta de tutorial.",
    difficulty: "fácil",
    impact: "Base para qualquer análise séria",
    skills: ["Excel avançado", "Lógica", "Tratamento de dados"],
    projects: ["Dashboard de gastos pessoais"],
    resources: [{ label: "Excel para análise de dados", type: "Trilha" }],
    checklist: [
      "Fórmulas de busca e condicionais",
      "Tabelas dinâmicas",
      "Primeiro dashboard próprio",
    ],
    xp: 300,
    why: "Antes de qualquer ferramenta sofisticada, quem lida com dados no dia a dia precisa dominar planilha de verdade — é o que 90% das vagas júnior testam primeiro.",
    impactLevel: "alto",
    milestone: "Primeira análise própria publicada",
    demandPct: 90,
    hours: 30,
    incomeWeight: 0,
  },
  {
    id: "step-2",
    title: "SQL para análise",
    goal: "Escrever consultas com joins, agregações e subqueries para responder perguntas de negócio.",
    difficulty: "médio",
    impact: "A habilidade mais pedida em vagas de dados júnior",
    skills: ["SQL", "PostgreSQL", "Modelagem"],
    projects: ["Consultas sobre base pública de dados"],
    resources: [{ label: "SQL para análise de dados", type: "Trilha" }],
    checklist: ["Joins e agregações", "Subqueries", "Otimização básica de consulta"],
    xp: 480,
    why: "SQL aparece em praticamente toda vaga de dados, do estágio ao sênior. É o divisor entre quem só sabe Excel e quem trabalha com dado de verdade.",
    impactLevel: "muito alto",
    milestone: "Pronto para testes técnicos de SQL",
    demandPct: 93,
    hours: 46,
    incomeWeight: 0.16,
  },
  {
    id: "step-3",
    title: "Python para dados",
    goal: "Automatizar limpeza e análise de dados com pandas em vez de planilha manual.",
    difficulty: "médio",
    impact: "Escala o que antes levava horas em planilha para minutos de script",
    skills: ["Python", "Pandas", "Automação"],
    projects: ["Pipeline de limpeza de uma base real"],
    resources: [{ label: "Python e pandas do zero", type: "Trilha" }],
    checklist: ["Manipulação com pandas", "Limpeza de dados sujos", "Script reprodutível"],
    xp: 520,
    why: "Quem só sabe Excel trava em bases grandes. Python com pandas é o que separa analista júnior de analista que escala.",
    impactLevel: "muito alto",
    milestone: "Primeira automação de análise própria",
    demandPct: 78,
    hours: 48,
    incomeWeight: 0.32,
  },
  {
    id: "step-4",
    title: "Visualização e storytelling de dados",
    goal: "Construir um dashboard que conta uma história clara para quem não é técnico.",
    difficulty: "médio",
    impact: "Transforma análise correta em decisão de negócio real",
    skills: ["Power BI", "Storytelling de dados"],
    projects: ["Dashboard executivo publicado"],
    resources: [{ label: "Dashboards que decisores realmente usam", type: "Guia" }],
    checklist: [
      "Dashboard com métricas certas",
      "Narrativa clara para leigo",
      "Publicação do case",
    ],
    xp: 400,
    why: "Análise certa que ninguém entende não vira decisão. Essa etapa é o que faz seu trabalho ser realmente usado.",
    impactLevel: "alto",
    milestone: "Portfólio com case de negócio real",
    demandPct: 66,
    hours: 26,
    incomeWeight: 0.48,
  },
  {
    id: "step-5",
    title: "Primeiros freelas de análise",
    goal: "Fechar projetos pequenos de análise ou automação para pequenos negócios.",
    difficulty: "médio",
    impact: "Renda extra e repertório de cliente real antes da vaga CLT",
    skills: ["Proposta comercial", "Escopo", "Entrega"],
    projects: ["Automação de relatório para pequeno negócio"],
    resources: [{ label: "Como precificar seu primeiro freela de dados", type: "Guia" }],
    checklist: ["Perfil em 2 plataformas", "10 propostas enviadas", "Primeiro projeto entregue"],
    xp: 580,
    why: "Freela paga a conta enquanto você estuda e prova, com cliente de verdade, que você resolve problema — não só executa exercício.",
    impactLevel: "alto",
    milestone: "Primeira renda extra com dados",
    demandPct: 38,
    hours: 55,
    incomeWeight: 0.62,
  },
  {
    id: "step-6",
    title: "Estatística aplicada",
    goal: "Interpretar métricas com rigor: significância, correlação vs. causalidade, amostragem.",
    difficulty: "difícil",
    impact: "Separa quem lê gráfico de quem entende o que o número realmente diz",
    skills: ["Estatística", "Interpretação de métricas"],
    projects: ["Teste A/B com dados simulados"],
    resources: [{ label: "Estatística para quem trabalha com dados", type: "Trilha" }],
    checklist: [
      "Testes de hipótese básicos",
      "Correlação vs. causalidade",
      "Relatório de um teste A/B",
    ],
    xp: 680,
    why: "Sem estatística, análise de dados vira opinião com gráfico bonito. É o que credibiliza tecnicamente o seu trabalho.",
    impactLevel: "alto",
    milestone: "Perfil competitivo para pleno",
    demandPct: 60,
    hours: 58,
    incomeWeight: 0.78,
  },
  {
    id: "step-7",
    title: "Candidaturas direcionadas",
    goal: "Currículo, LinkedIn e portfólio de cases alinhados à vaga de dados que você quer.",
    difficulty: "médio",
    impact: "Etapa que converte aprendizado em salário",
    skills: ["Entrevista técnica", "Posicionamento"],
    projects: ["Simulações de case técnico"],
    resources: [{ label: "Como é uma entrevista de dados", type: "Guia" }],
    checklist: ["Currículo revisado", "LinkedIn otimizado", "Lista de empresas-alvo"],
    xp: 620,
    why: "Candidatura é funil: volume qualificado com portfólio real é o que fecha a diferença até a sua meta de renda.",
    impactLevel: "muito alto",
    milestone: "Primeira oferta formal na área",
    demandPct: 100,
    hours: 28,
    incomeWeight: 1,
  },
];

const DESIGN: TemplateStep[] = [
  {
    id: "step-1",
    title: "Fundamentos de UI",
    goal: "Dominar hierarquia visual, espaçamento, tipografia e cor com intenção, não no achismo.",
    difficulty: "fácil",
    impact: "Base que separa design amador de design com critério",
    skills: ["Hierarquia visual", "Tipografia", "Figma básico"],
    projects: ["Redesign de uma tela existente"],
    resources: [{ label: "Fundamentos de UI — trilha guiada", type: "Trilha" }],
    checklist: [
      "Sistema de tipografia próprio",
      "Paleta com contraste correto",
      "Primeiro redesign",
    ],
    xp: 300,
    why: "Sem fundamento visual sólido, todo projeto depende de sorte. É aqui que você aprende a justificar cada escolha, não só imitar referência.",
    impactLevel: "alto",
    milestone: "Primeiro redesign com critério visual",
    demandPct: 88,
    hours: 32,
    incomeWeight: 0,
  },
  {
    id: "step-2",
    title: "Pesquisa e UX",
    goal: "Conduzir uma pesquisa simples com usuários e transformar insight em decisão de tela.",
    difficulty: "médio",
    impact: "O que separa quem só desenha de quem resolve problema real",
    skills: ["Pesquisa com usuários", "Wireframe", "UX"],
    projects: ["Estudo de caso com pesquisa real"],
    resources: [{ label: "Pesquisa de UX na prática", type: "Trilha" }],
    checklist: [
      "5 entrevistas com usuários",
      "Wireframes de baixa fidelidade",
      "Decisão justificada por dado",
    ],
    xp: 460,
    why: "Recrutador de UX quer ver processo, não só tela bonita. Pesquisa é a parte que prova que você pensa, não só executa.",
    impactLevel: "muito alto",
    milestone: "Primeiro case com pesquisa documentada",
    demandPct: 76,
    hours: 44,
    incomeWeight: 0.16,
  },
  {
    id: "step-3",
    title: "Design system",
    goal: "Construir uma biblioteca de componentes reutilizável e consistente no Figma.",
    difficulty: "médio",
    impact: "Habilidade que times de produto maiores exigem diretamente",
    skills: ["Design system", "Componentização", "Figma avançado"],
    projects: ["Design system de um produto fictício"],
    resources: [{ label: "Design systems na prática", type: "Guia" }],
    checklist: [
      "Biblioteca de componentes",
      "Tokens de cor e espaçamento",
      "Documentação do sistema",
    ],
    xp: 500,
    why: "Empresa com produto de verdade não trabalha com tela solta — trabalha com sistema. Isso é o que te tira do nível 'freela avulso'.",
    impactLevel: "alto",
    milestone: "Portfólio com sistema completo",
    demandPct: 62,
    hours: 42,
    incomeWeight: 0.32,
  },
  {
    id: "step-4",
    title: "Protótipo navegável",
    goal: "Entregar um fluxo completo, navegável e testável, do zero ao protótipo final.",
    difficulty: "médio",
    impact: "É o que fecha um case de portfólio de forma profissional",
    skills: ["Prototipagem", "Micro-interações"],
    projects: ["Fluxo completo de um app fictício"],
    resources: [{ label: "Prototipagem avançada no Figma", type: "Trilha" }],
    checklist: ["Fluxo ponta a ponta navegável", "Micro-interações", "Teste com 3 usuários"],
    xp: 440,
    why: "Print estático não convence mais ninguém. Um protótipo navegável e testado é o que hoje diferencia um portfólio contratável.",
    impactLevel: "alto",
    milestone: "Case de portfólio pronto para mostrar",
    demandPct: 70,
    hours: 30,
    incomeWeight: 0.48,
  },
  {
    id: "step-5",
    title: "Primeiros freelas de design",
    goal: "Fechar 2 projetos pequenos pagos, do briefing à entrega final.",
    difficulty: "médio",
    impact: "Renda extra e prova de entrega com cliente real",
    skills: ["Proposta comercial", "Briefing", "Entrega"],
    projects: ["Redesign para pequeno negócio"],
    resources: [{ label: "Como precificar seu primeiro freela de design", type: "Guia" }],
    checklist: ["Perfil em 2 plataformas", "10 propostas enviadas", "Primeiro projeto entregue"],
    xp: 580,
    why: "Freela paga a conta enquanto você constrói portfólio com cliente de verdade, que exige e dá feedback — diferente de projeto de curso.",
    impactLevel: "alto",
    milestone: "Primeira renda extra com design",
    demandPct: 44,
    hours: 55,
    incomeWeight: 0.62,
  },
  {
    id: "step-6",
    title: "Handoff e colaboração com dev",
    goal: "Entregar telas prontas para implementação sem retrabalho de ida e volta.",
    difficulty: "difícil",
    impact: "Falta disso é a maior reclamação de squads sobre designers júnior",
    skills: ["Handoff", "Specs para dev", "Colaboração"],
    projects: ["Handoff completo de um projeto real"],
    resources: [{ label: "Handoff sem retrabalho", type: "Guia" }],
    checklist: [
      "Specs completas de um fluxo",
      "Reunião de handoff simulada",
      "Ajuste pós-implementação",
    ],
    xp: 620,
    why: "Design que trava na implementação não vira produto. Saber entregar bem pra dev é o que te tira do nível júnior raso.",
    impactLevel: "alto",
    milestone: "Perfil competitivo para pleno",
    demandPct: 55,
    hours: 50,
    incomeWeight: 0.78,
  },
  {
    id: "step-7",
    title: "Candidaturas direcionadas",
    goal: "Portfólio, currículo e LinkedIn alinhados às vagas de design que você quer.",
    difficulty: "médio",
    impact: "Etapa que converte aprendizado em salário",
    skills: ["Apresentação de portfólio", "Posicionamento"],
    projects: ["Simulações de apresentação de case"],
    resources: [{ label: "Como apresentar um case em entrevista", type: "Guia" }],
    checklist: ["Portfólio revisado", "LinkedIn otimizado", "Lista de empresas-alvo"],
    xp: 600,
    why: "Candidatura é funil: volume qualificado com portfólio bem apresentado é o que fecha a diferença até a sua meta de renda.",
    impactLevel: "muito alto",
    milestone: "Primeira oferta formal na área",
    demandPct: 100,
    hours: 28,
    incomeWeight: 1,
  },
];

const MARKETING: TemplateStep[] = [
  {
    id: "step-1",
    title: "Fundamentos de marketing digital",
    goal: "Entender funil, métricas e canais o suficiente para não depender só de achismo.",
    difficulty: "fácil",
    impact: "Base para qualquer especialização de marketing depois",
    skills: ["Funil de marketing", "Métricas", "SEO básico"],
    projects: ["Auditoria de um perfil ou site real"],
    resources: [{ label: "Marketing digital do zero", type: "Trilha" }],
    checklist: [
      "Mapear um funil real",
      "Entender as métricas certas",
      "Primeira auditoria própria",
    ],
    xp: 300,
    why: "Sem entender funil e métrica, toda ação de marketing é tiro no escuro. É aqui que você troca achismo por critério.",
    impactLevel: "alto",
    milestone: "Primeira auditoria própria entregue",
    demandPct: 85,
    hours: 30,
    incomeWeight: 0,
  },
  {
    id: "step-2",
    title: "Tráfego pago",
    goal: "Rodar e otimizar uma campanha real de anúncios com orçamento controlado.",
    difficulty: "médio",
    impact: "Uma das habilidades mais bem pagas dentro de marketing",
    skills: ["Tráfego pago", "Meta Ads", "Otimização de campanha"],
    projects: ["Campanha de teste com orçamento pequeno"],
    resources: [{ label: "Tráfego pago na prática", type: "Trilha" }],
    checklist: ["Estrutura de campanha", "Segmentação de público", "Relatório de resultado"],
    xp: 500,
    why: "Tráfego pago é a habilidade de marketing com correlação mais direta a salário — quem sabe gastar bem o dinheiro de outro é raro.",
    impactLevel: "muito alto",
    milestone: "Pronto para vagas júnior de performance",
    demandPct: 72,
    hours: 46,
    incomeWeight: 0.16,
  },
  {
    id: "step-3",
    title: "Copywriting",
    goal: "Escrever textos que convertem, não só que soam bonitos.",
    difficulty: "médio",
    impact: "Habilidade transversal usada em todo canal de marketing",
    skills: ["Copywriting", "Gatilhos de conversão"],
    projects: ["Página de vendas fictícia"],
    resources: [{ label: "Copywriting que converte", type: "Trilha" }],
    checklist: [
      "Estrutura de página de vendas",
      "3 variações de headline testadas",
      "Copy revisado por outra pessoa",
    ],
    xp: 420,
    why: "Tráfego bom com copy ruim queima dinheiro. Essa etapa é o que faz o resto do seu trabalho realmente performar.",
    impactLevel: "alto",
    milestone: "Portfólio com peça de copy própria",
    demandPct: 64,
    hours: 28,
    incomeWeight: 0.32,
  },
  {
    id: "step-4",
    title: "Analytics e dados de marketing",
    goal: "Ler dashboard de performance e recomendar ação a partir do número, não da intuição.",
    difficulty: "médio",
    impact: "Diferencia quem executa de quem também decide",
    skills: ["Google Analytics", "Leitura de dados"],
    projects: ["Relatório de performance de uma campanha"],
    resources: [{ label: "Analytics para marketing", type: "Guia" }],
    checklist: [
      "Configurar métricas certas",
      "Relatório com recomendação",
      "Apresentação do resultado",
    ],
    xp: 440,
    why: "Marketing sem leitura de dado vira opinião com gráfico. É o que credibiliza tecnicamente as suas campanhas.",
    impactLevel: "alto",
    milestone: "Case com decisão baseada em dado",
    demandPct: 58,
    hours: 32,
    incomeWeight: 0.48,
  },
  {
    id: "step-5",
    title: "Primeiros freelas de marketing",
    goal: "Fechar 2 projetos pequenos: gestão de redes ou campanha para pequeno negócio.",
    difficulty: "médio",
    impact: "Renda extra e prova de entrega com cliente real",
    skills: ["Proposta comercial", "Gestão de cliente", "Entrega"],
    projects: ["Gestão de redes de pequeno negócio"],
    resources: [{ label: "Como precificar seu primeiro freela de marketing", type: "Guia" }],
    checklist: ["Perfil em 2 plataformas", "10 propostas enviadas", "Primeiro projeto entregue"],
    xp: 560,
    why: "Freela paga a conta enquanto você constrói case com cliente de verdade, que cobra resultado — diferente de exercício de curso.",
    impactLevel: "alto",
    milestone: "Primeira renda extra com marketing",
    demandPct: 40,
    hours: 55,
    incomeWeight: 0.62,
  },
  {
    id: "step-6",
    title: "Estratégia de canal",
    goal: "Planejar um mix de canais coerente com objetivo de negócio, não só executar campanha isolada.",
    difficulty: "difícil",
    impact: "Salto do nível júnior-executor para o nível que planeja",
    skills: ["Estratégia de marketing", "Planejamento de canal"],
    projects: ["Plano de marketing trimestral fictício"],
    resources: [{ label: "Estratégia de marketing multicanal", type: "Trilha" }],
    checklist: [
      "Plano de canais justificado",
      "Orçamento distribuído por canal",
      "Metas por canal definidas",
    ],
    xp: 660,
    why: "Quem só executa campanha isolada fica no teto júnior. Pensar estratégia de canal é o que abre vaga pleno.",
    impactLevel: "alto",
    milestone: "Perfil competitivo para pleno",
    demandPct: 50,
    hours: 52,
    incomeWeight: 0.78,
  },
  {
    id: "step-7",
    title: "Candidaturas direcionadas",
    goal: "Portfólio de campanhas, currículo e LinkedIn alinhados à vaga que você quer.",
    difficulty: "médio",
    impact: "Etapa que converte aprendizado em salário",
    skills: ["Apresentação de resultados", "Posicionamento"],
    projects: ["Simulações de entrevista de marketing"],
    resources: [{ label: "Como apresentar resultado de campanha em entrevista", type: "Guia" }],
    checklist: ["Currículo revisado", "LinkedIn otimizado", "Lista de empresas-alvo"],
    xp: 600,
    why: "Candidatura é funil: volume qualificado com resultado documentado é o que fecha a diferença até a sua meta de renda.",
    impactLevel: "muito alto",
    milestone: "Primeira oferta formal na área",
    demandPct: 100,
    hours: 28,
    incomeWeight: 1,
  },
];

/** Usado para as áreas sem template dedicado ainda (sales, finance, engineering, admin, audiovisual, other). */
const GENERIC: TemplateStep[] = [
  {
    id: "step-1",
    title: "Excel e organização de dados",
    goal: "Organizar, limpar e analisar planilhas com fórmulas e tabelas dinâmicas.",
    difficulty: "fácil",
    impact: "Habilidade exigida em praticamente qualquer função de escritório",
    skills: ["Excel avançado", "Organização de dados"],
    projects: ["Planilha de controle real do seu dia a dia"],
    resources: [{ label: "Excel para o mercado de trabalho", type: "Trilha" }],
    checklist: [
      "Fórmulas condicionais e de busca",
      "Tabelas dinâmicas",
      "Primeira planilha de controle",
    ],
    xp: 280,
    why: "É a habilidade mais universalmente exigida, e a maioria só sabe o básico. Dominar de verdade já te destaca.",
    impactLevel: "alto",
    milestone: "Primeira planilha de controle própria",
    demandPct: 82,
    hours: 26,
    incomeWeight: 0,
  },
  {
    id: "step-2",
    title: "Comunicação escrita profissional",
    goal: "Escrever e-mails, relatórios e propostas claros, objetivos e sem ruído.",
    difficulty: "fácil",
    impact: "Diferencia quem é promovido de quem fica parado",
    skills: ["Comunicação escrita", "Redação de relatórios"],
    projects: ["Relatório real de um processo do seu trabalho"],
    resources: [{ label: "Comunicação escrita para o trabalho", type: "Guia" }],
    checklist: [
      "Reescrever um e-mail real",
      "Estrutura de relatório objetivo",
      "Feedback de terceiro sobre um texto",
    ],
    xp: 260,
    why: "Boa parte das oportunidades perdidas não é por falta de competência técnica, é por comunicação confusa. Custa pouco melhorar e o impacto é imediato.",
    impactLevel: "médio",
    milestone: "Comunicação revisada e mais clara",
    demandPct: 70,
    hours: 18,
    incomeWeight: 0.16,
  },
  {
    id: "step-3",
    title: "Ferramentas de produtividade e automação leve",
    goal: "Automatizar tarefas repetitivas com planilhas, formulários ou ferramentas no-code.",
    difficulty: "médio",
    impact: "Libera tempo e mostra iniciativa acima do esperado no cargo",
    skills: ["Automação no-code", "Ferramentas de produtividade"],
    projects: ["Automatizar uma tarefa repetitiva real"],
    resources: [{ label: "Automação sem programar", type: "Trilha" }],
    checklist: [
      "Mapear uma tarefa repetitiva",
      "Automatizar com ferramenta no-code",
      "Medir tempo economizado",
    ],
    xp: 420,
    why: "Quem automatiza o próprio trabalho aparece. É a etapa que começa a te diferenciar dos colegas na mesma função.",
    impactLevel: "alto",
    milestone: "Primeira automação real implementada",
    demandPct: 55,
    hours: 34,
    incomeWeight: 0.32,
  },
  {
    id: "step-4",
    title: "Análise de dados aplicada à sua área",
    goal: "Usar dados reais do seu trabalho para embasar uma recomendação concreta.",
    difficulty: "médio",
    impact: "Transforma execução em contribuição estratégica",
    skills: ["Análise de dados", "Leitura de indicadores"],
    projects: ["Relatório com recomendação baseada em dado"],
    resources: [{ label: "Análise de dados para não-analistas", type: "Guia" }],
    checklist: [
      "Levantar dados reais da sua função",
      "Análise com conclusão clara",
      "Apresentar a recomendação",
    ],
    xp: 460,
    why: "Quem traz dado junto da opinião é ouvido diferente. É o que separa quem executa de quem também é consultado.",
    impactLevel: "alto",
    milestone: "Primeira recomendação baseada em dado",
    demandPct: 60,
    hours: 36,
    incomeWeight: 0.48,
  },
  {
    id: "step-5",
    title: "Renda extra paralela",
    goal: "Testar uma fonte de renda extra alinhada às suas novas habilidades.",
    difficulty: "médio",
    impact: "Renda extra no curto prazo, sem depender só de uma promoção",
    skills: ["Proposta comercial", "Gestão do próprio tempo"],
    projects: ["Primeiro serviço extra prestado"],
    resources: [{ label: "Como começar uma renda extra sem largar o principal", type: "Guia" }],
    checklist: [
      "Definir um serviço ou produto simples",
      "Primeira divulgação",
      "Primeira entrega paga",
    ],
    xp: 520,
    why: "Enquanto a promoção ou a nova vaga não vêm, uma renda extra bem escolhida já move o ponteiro na direção da sua meta.",
    impactLevel: "médio",
    milestone: "Primeira renda extra real",
    demandPct: 35,
    hours: 50,
    incomeWeight: 0.62,
  },
  {
    id: "step-6",
    title: "Gestão de projetos e prazos",
    goal: "Planejar e entregar uma iniciativa própria do início ao fim, com prazo cumprido.",
    difficulty: "difícil",
    impact: "É o que abre espaço para cargos de coordenação",
    skills: ["Gestão de projetos", "Planejamento"],
    projects: ["Um projeto próprio do início ao fim"],
    resources: [{ label: "Gestão de projetos na prática", type: "Trilha" }],
    checklist: [
      "Planejar etapas e prazos",
      "Executar com acompanhamento",
      "Entregar dentro do prazo",
    ],
    xp: 600,
    why: "Quem entrega prazo e escopo de forma confiável é quem é considerado pra liderar depois. É o salto de nível mais concreto que existe.",
    impactLevel: "alto",
    milestone: "Perfil competitivo para o próximo nível",
    demandPct: 48,
    hours: 48,
    incomeWeight: 0.78,
  },
  {
    id: "step-7",
    title: "Posicionamento e candidaturas",
    goal: "Currículo, LinkedIn e argumento claro sobre o que você entrega de diferente agora.",
    difficulty: "médio",
    impact: "Etapa que converte aprendizado em salário",
    skills: ["Posicionamento profissional", "Entrevista"],
    projects: ["Simulações de entrevista ou negociação"],
    resources: [{ label: "Como pedir aumento ou mudar de vaga com argumento real", type: "Guia" }],
    checklist: ["Currículo revisado", "LinkedIn atualizado", "Lista de próximos passos concretos"],
    xp: 560,
    why: "Toda a rota até aqui não vale nada se não virar conversa concreta sobre renda — seja promoção, nova vaga ou proposta melhor.",
    impactLevel: "muito alto",
    milestone: "Primeira conversa formal sobre a meta de renda",
    demandPct: 100,
    hours: 26,
    incomeWeight: 1,
  },
];

const TEMPLATES: Record<AreaId, TemplateStep[]> = {
  tech: TECH,
  ai: TECH,
  data: DATA,
  design: DESIGN,
  marketing: MARKETING,
  sales: GENERIC,
  finance: GENERIC,
  engineering: GENERIC,
  admin: GENERIC,
  audiovisual: GENERIC,
  other: GENERIC,
};

/** Etapas com prereq linear simples: cada uma depende só da anterior — igual à rota original. */
function withPrereqs(steps: TemplateStep[]): (TemplateStep & { prereqs: string[] })[] {
  return steps.map((s, i) => ({ ...s, prereqs: i === 0 ? [] : [steps[i - 1]!.id] }));
}

const EXPERIENCE_SKIP: Record<ExperienceId, number> = {
  none: 0,
  lt1: 0,
  "1to3": 1,
  "3to5": 1,
  gt5: 2,
};

function roundToTen(n: number): number {
  return Math.round(n / 10) * 10;
}

/**
 * Gera a rota a partir do perfil real do onboarding. Determinístico: mesma entrada, mesma
 * rota — nada de aleatoriedade nem "IA" fingida.
 */
export function generateRoute(profile: OnboardingProfile): RouteStep[] {
  const area = profile.desiredAreas[0] ?? "tech";
  const template = withPrereqs(TEMPLATES[area] ?? GENERIC);

  const current = profile.income.noIncome ? 0 : (profile.income.current ?? 0);
  const target = Math.max(profile.income.target ?? current + 1000, current + 500);

  const horizon = horizons.find((h) => h.id === profile.income.horizon)?.months ?? 10;
  const hoursPerWeek = Math.max(2, profile.study.hoursPerWeek || 7);

  // Experiência avançada pula as primeiras etapas de fundamentos, mas nunca menos de 3 restantes.
  const skip = Math.min(
    EXPERIENCE_SKIP[profile.experience ?? "none"],
    Math.max(0, template.length - 3),
  );
  const active = template.slice(skip);

  let cumulativeWeek = 1;
  return active.map((s, i) => {
    const incomeAfter = roundToTen(current + (target - current) * s.incomeWeight);
    const week = cumulativeWeek;
    cumulativeWeek += Math.max(1, Math.round(s.hours / hoursPerWeek));
    const etaWeeks = Math.max(1, Math.round(s.hours / hoursPerWeek));

    return {
      id: s.id,
      order: i + 1,
      title: s.title,
      goal: s.goal,
      eta: etaWeeks === 1 ? "1 semana" : `${etaWeeks} semanas`,
      difficulty: s.difficulty,
      impact: s.impact,
      incomeAfter,
      skills: s.skills,
      projects: s.projects,
      resources: s.resources,
      checklist: s.checklist.map((label, ci) => ({ id: `c${ci + 1}`, label, done: false })),
      xp: s.xp,
      status: i === 0 ? "em andamento" : "bloqueado",
      why: s.why,
      impactLevel: s.impactLevel,
      prereqs: i === 0 ? [] : [active[i - 1]!.id],
      milestone: s.milestone,
      demandPct: s.demandPct,
      hours: s.hours,
      week,
    };
  });
}

const AREA_ROLE_LABEL: Record<AreaId, string> = {
  tech: "Desenvolvedor(a)",
  ai: "Especialista em IA aplicada",
  data: "Analista de Dados",
  design: "Designer de Produto",
  marketing: "Analista de Marketing",
  sales: "Profissional de Vendas",
  finance: "Analista Financeiro",
  engineering: "Engenheiro(a)",
  admin: "Analista Administrativo",
  audiovisual: "Profissional Audiovisual",
  other: "Profissional especializado",
};

export function roleLabelForArea(area: AreaId | undefined): string {
  return AREA_ROLE_LABEL[area ?? "tech"];
}
