-- GERADO por scripts/gerar-seed-catalogo.ts — não edite à mão.
-- Fonte de verdade: src/lib/catalog.ts. Para atualizar, mude lá e rode o script de novo.
--
-- Rode depois de supabase/schema.sql. Reexecutar é seguro: o slug é único e o on conflict
-- atualiza a linha em vez de duplicar.

insert into public.pathly_resources
  (slug, title, url, kind, provider, language, is_free, topics, areas, level, summary, source, source_license)
values
  ('curso-em-video-python', 'Curso de Python — Curso em Vídeo', 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6', 'video', 'Curso em Vídeo', 'pt', true, array['Python', 'Lógica'], array['tech', 'data', 'ai'], 'iniciante', 'Python do zero em português, com exercícios a cada aula. É o caminho mais usado por quem começa no Brasil.', 'Curso em Vídeo', 'link + descrição própria'),
  ('freecodecamp-python', 'Scientific Computing with Python', 'https://www.freecodecamp.org/learn/scientific-computing-with-python/', 'curso', 'freeCodeCamp', 'en', true, array['Python', 'Lógica'], array['tech', 'data', 'ai'], 'iniciante', 'Certificação gratuita com projetos obrigatórios no fim — bom para provar que você aprendeu, não só assistiu.', 'freeCodeCamp', 'BSD-3-Clause'),
  ('python-docs-tutorial', 'Tutorial oficial do Python', 'https://docs.python.org/pt-br/3/tutorial/', 'doc', 'Python Software Foundation', 'pt', true, array['Python'], array['tech', 'data', 'ai'], null, 'A documentação oficial traduzida. Serve de consulta quando o vídeo não explica o detalhe.', 'Python Software Foundation', 'link + descrição própria'),
  ('pro-git-livro', 'Pro Git (livro completo)', 'https://git-scm.com/book/pt-br/v2', 'livro', 'git-scm', 'pt', true, array['Git', 'Git básico', 'Git avançado'], array['tech', 'data', 'ai'], null, 'O livro de referência de Git, gratuito e em português. Os três primeiros capítulos já cobrem o dia a dia.', 'git-scm', 'link + descrição própria'),
  ('github-skills', 'GitHub Skills', 'https://skills.github.com/', 'curso', 'GitHub', 'en', true, array['Git', 'Git básico', 'README'], array['tech', 'data', 'design', 'ai'], 'iniciante', 'Exercícios práticos dentro do próprio GitHub: você aprende abrindo pull request de verdade.', 'GitHub', 'link + descrição própria'),
  ('fastapi-docs', 'Documentação do FastAPI', 'https://fastapi.tiangolo.com/pt/', 'doc', 'FastAPI', 'pt', true, array['FastAPI', 'REST', 'HTTP'], array['tech', 'ai'], 'intermediário', 'Tutorial oficial em português, do primeiro endpoint até autenticação. É documentação e curso ao mesmo tempo.', 'FastAPI', 'link + descrição própria'),
  ('mdn-http', 'HTTP — MDN Web Docs', 'https://developer.mozilla.org/pt-BR/docs/Web/HTTP', 'doc', 'MDN', 'pt', true, array['HTTP', 'REST'], array['tech'], null, 'Referência de métodos, status e cabeçalhos HTTP. É o que você vai consultar em toda entrevista técnica.', 'MDN', 'link + descrição própria'),
  ('freecodecamp-backend', 'Back End Development and APIs', 'https://www.freecodecamp.org/learn/back-end-development-and-apis/', 'curso', 'freeCodeCamp', 'en', true, array['REST', 'Node.js', 'HTTP'], array['tech'], 'intermediário', 'Cinco APIs construídas do zero, com certificação no fim. Vira portfólio direto.', 'freeCodeCamp', 'BSD-3-Clause'),
  ('sqlbolt', 'SQLBolt — exercícios interativos', 'https://sqlbolt.com/', 'curso', 'SQLBolt', 'en', true, array['SQL', 'Joins e agregações'], array['tech', 'data'], 'iniciante', 'Você escreve SQL no navegador e vê o resultado na hora. Cobre join e agregação em uma tarde.', 'SQLBolt', 'link + descrição própria'),
  ('postgres-tutorial', 'PostgreSQL Tutorial', 'https://neon.com/postgresql/tutorial', 'curso', 'PostgreSQL Tutorial', 'en', true, array['PostgreSQL', 'SQL', 'Modelagem'], array['tech', 'data'], 'intermediário', 'Do básico a índices e performance, com base de exemplo para praticar.', 'PostgreSQL Tutorial', 'link + descrição própria'),
  ('freecodecamp-relational-db', 'Relational Database', 'https://www.freecodecamp.org/learn/relational-database/', 'curso', 'freeCodeCamp', 'en', true, array['SQL', 'PostgreSQL', 'Modelagem'], array['tech', 'data'], 'intermediário', 'Banco relacional direto no terminal, com Postgres e Git. Mais próximo do trabalho real que exercício de tela.', 'freeCodeCamp', 'BSD-3-Clause'),
  ('docker-get-started', 'Docker — Get Started', 'https://docs.docker.com/get-started/', 'doc', 'Docker', 'en', true, array['Docker', 'CI/CD'], array['tech', 'data'], 'avançado', 'Guia oficial: da primeira imagem até subir uma aplicação com vários serviços.', 'Docker', 'link + descrição própria'),
  ('github-actions-docs', 'GitHub Actions — documentação', 'https://docs.github.com/pt/actions', 'doc', 'GitHub', 'pt', true, array['CI/CD', 'Pipeline de CI'], array['tech', 'data'], 'avançado', 'CI gratuito para repositório público. É o caminho mais curto para ter pipeline no portfólio.', 'GitHub', 'link + descrição própria'),
  ('kaggle-learn', 'Kaggle Learn', 'https://www.kaggle.com/learn', 'curso', 'Kaggle', 'en', true, array['Pandas', 'Python', 'Machine Learning', 'Análise de dados'], array['data', 'ai'], 'intermediário', 'Módulos curtos com notebook rodando no navegador, sem instalar nada. Pandas e SQL em poucas horas.', 'Kaggle', 'link + descrição própria'),
  ('pandas-getting-started', 'Pandas — guia de introdução', 'https://pandas.pydata.org/docs/getting_started/index.html', 'doc', 'pandas', 'en', true, array['Pandas', 'Tratamento de dados'], array['data', 'ai'], null, 'Documentação oficial com comparações para quem vem do Excel e do SQL.', 'pandas', 'link + descrição própria'),
  ('freecodecamp-data-analysis', 'Data Analysis with Python', 'https://www.freecodecamp.org/learn/data-analysis-with-python/', 'curso', 'freeCodeCamp', 'en', true, array['Pandas', 'Python', 'Análise de dados'], array['data'], 'intermediário', 'Análise com pandas e numpy, terminando em cinco projetos avaliados.', 'freeCodeCamp', 'BSD-3-Clause'),
  ('power-bi-learn', 'Microsoft Learn — Power BI', 'https://learn.microsoft.com/pt-br/training/powerplatform/power-bi', 'curso', 'Microsoft', 'pt', true, array['Power BI', 'Storytelling de dados', 'Excel avançado'], array['data', 'finance', 'admin'], 'iniciante', 'Trilha oficial em português, do primeiro relatório ao painel publicado.', 'Microsoft', 'link + descrição própria'),
  ('figma-learn', 'Figma — Learn Design', 'https://www.figma.com/resource-library/', 'curso', 'Figma', 'en', true, array['Figma básico', 'Figma avançado', 'UI Design'], array['design'], 'iniciante', 'Material da própria Figma sobre fundamentos de interface e uso da ferramenta.', 'Figma', 'link + descrição própria'),
  ('laws-of-ux', 'Laws of UX', 'https://lawsofux.com/', 'artigo', 'Laws of UX', 'pt', true, array['UX', 'Hierarquia visual', 'Pesquisa com usuários'], array['design'], null, 'Princípios de usabilidade explicados em uma página cada, em português. Dá vocabulário para justificar decisão de tela.', 'Laws of UX', 'link + descrição própria'),
  ('material-design', 'Material Design 3', 'https://m3.material.io/', 'doc', 'Google', 'en', true, array['Design system', 'Componentização', 'Tokens de cor e espaçamento'], array['design'], 'intermediário', 'Design system completo e público — serve de referência de como documentar o seu.', 'Google', 'link + descrição própria'),
  ('google-skillshop', 'Google Skillshop', 'https://skillshop.withgoogle.com/', 'curso', 'Google', 'pt', true, array['Tráfego pago', 'Google Analytics', 'Métricas'], array['marketing', 'sales'], 'iniciante', 'Certificações oficiais gratuitas de Ads e Analytics, reconhecidas em processo seletivo.', 'Google', 'link + descrição própria'),
  ('meta-blueprint', 'Meta Blueprint', 'https://www.facebook.com/business/learn', 'curso', 'Meta', 'pt', true, array['Meta Ads', 'Tráfego pago', 'Otimização de campanha'], array['marketing', 'sales'], 'iniciante', 'Trilhas gratuitas de anúncios no Instagram e Facebook, direto de quem faz a plataforma.', 'Meta', 'link + descrição própria'),
  ('google-analytics-academy', 'Google Analytics — central de ajuda', 'https://support.google.com/analytics/answer/9304153', 'doc', 'Google', 'pt', true, array['Google Analytics', 'Leitura de dados', 'Funil de marketing'], array['marketing'], null, 'Como configurar e ler os relatórios do GA4, que é o que as vagas pedem hoje.', 'Google', 'link + descrição própria'),
  ('free-programming-books', 'Free Programming Books (pt-BR)', 'https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-pt_BR.md', 'livro', 'Ebook Foundation', 'pt', true, array['Python', 'SQL', 'Git', 'Lógica', 'JavaScript'], array['tech', 'data', 'ai', 'other'], null, 'Lista mantida pela comunidade com centenas de livros gratuitos em português, por linguagem.', 'Ebook Foundation', 'CC-BY-4.0'),
  ('roadmap-sh', 'roadmap.sh', 'https://roadmap.sh/', 'artigo', 'roadmap.sh', 'en', true, array['Posicionamento', 'Lógica'], array['tech', 'data', 'design', 'ai'], null, 'Mapas visuais de carreira para comparar com a sua rota e ver o que vem depois.', 'roadmap.sh', 'link + descrição própria'),
  ('grow-google', 'Cresça com o Google', 'https://grow.google/intl/pt-BR/', 'curso', 'Google', 'pt', true, array['Posicionamento', 'LinkedIn otimizado', 'Currículo revisado', 'Entrevista'], array['tech', 'data', 'design', 'marketing', 'sales', 'admin', 'other'], null, 'Trilhas gratuitas em português sobre currículo, entrevista e primeiros passos de carreira.', 'Google', 'link + descrição própria')
on conflict (slug) do update set
  title = excluded.title,
  url = excluded.url,
  kind = excluded.kind,
  provider = excluded.provider,
  language = excluded.language,
  is_free = excluded.is_free,
  topics = excluded.topics,
  areas = excluded.areas,
  level = excluded.level,
  summary = excluded.summary,
  source = excluded.source,
  source_license = excluded.source_license;
