/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiApisRouteImport } from './routes/api.apis'
import { Route as ApiAssinaturaRouteImport } from './routes/api.assinatura'
import { Route as ApiBancoRouteImport } from './routes/api.banco'
import { Route as ApiBlueprintRouteImport } from './routes/api.blueprint'
import { Route as ApiEtapaRouteImport } from './routes/api.etapa'
import { Route as ApiLicaoRouteImport } from './routes/api.licao'
import { Route as ApiPraticaRouteImport } from './routes/api.pratica'
import { Route as ApiRotaRouteImport } from './routes/api.rota'
import { Route as ApiSegurancaRouteImport } from './routes/api.seguranca'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBlueprintsRouteImport } from './routes/app.blueprints'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppHabilidadesRouteImport } from './routes/app.habilidades'
import { Route as AppOportunidadesRouteImport } from './routes/app.oportunidades'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPlanosRouteImport } from './routes/app.planos'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppRevisarRouteImport } from './routes/app.revisar'
import { Route as AppRotaRouteImport } from './routes/app.rota'
import { Route as AppApiIdRouteImport } from './routes/app.api.$id'
import { Route as AppAprenderActivityIdRouteImport } from './routes/app.aprender.$activityId'
import { Route as AppBancoIdRouteImport } from './routes/app.banco.$id'
import { Route as AppBlueprintIdRouteImport } from './routes/app.blueprint.$id'
import { Route as AppRoadmapIdRouteImport } from './routes/app.roadmap.$id'
import { Route as AppSegurancaIdRouteImport } from './routes/app.seguranca.$id'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApisRoute = ApiApisRouteImport.update({
  id: '/api/apis',
  path: '/api/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssinaturaRoute = ApiAssinaturaRouteImport.update({
  id: '/api/assinatura',
  path: '/api/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBancoRoute = ApiBancoRouteImport.update({
  id: '/api/banco',
  path: '/api/banco',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintRoute = ApiBlueprintRouteImport.update({
  id: '/api/blueprint',
  path: '/api/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEtapaRoute = ApiEtapaRouteImport.update({
  id: '/api/etapa',
  path: '/api/etapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicaoRoute = ApiLicaoRouteImport.update({
  id: '/api/licao',
  path: '/api/licao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPraticaRoute = ApiPraticaRouteImport.update({
  id: '/api/pratica',
  path: '/api/pratica',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRotaRoute = ApiRotaRouteImport.update({
  id: '/api/rota',
  path: '/api/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSegurancaRoute = ApiSegurancaRouteImport.update({
  id: '/api/seguranca',
  path: '/api/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlueprintsRoute = AppBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppHabilidadesRoute = AppHabilidadesRouteImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisarRoute = AppRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AppRoute,
} as any)
const AppRotaRoute = AppRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AppRoute,
} as any)
const AppApiIdRoute = AppApiIdRouteImport.update({
  id: '/api/$id',
  path: '/api/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAprenderActivityIdRoute = AppAprenderActivityIdRouteImport.update({
  id: '/aprender/$activityId',
  path: '/aprender/$activityId',
  getParentRoute: () => AppRoute,
} as any)
const AppBancoIdRoute = AppBancoIdRouteImport.update({
  id: '/banco/$id',
  path: '/banco/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBlueprintIdRoute = AppBlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapIdRoute = AppRoadmapIdRouteImport.update({
  id: '/roadmap/$id',
  path: '/roadmap/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurancaIdRoute = AppSegurancaIdRouteImport.update({
  id: '/seguranca/$id',
  path: '/seguranca/$id',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/apis': typeof ApiApisRoute
  '/api/assinatura': typeof ApiAssinaturaRoute
  '/api/banco': typeof ApiBancoRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/etapa': typeof ApiEtapaRoute
  '/api/licao': typeof ApiLicaoRoute
  '/api/pratica': typeof ApiPraticaRoute
  '/api/rota': typeof ApiRotaRoute
  '/api/seguranca': typeof ApiSegurancaRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/app/blueprints': typeof AppBlueprintsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/habilidades': typeof AppHabilidadesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/revisar': typeof AppRevisarRoute
  '/app/rota': typeof AppRotaRoute
  '/app/': typeof AppIndexRoute
  '/app/api/$id': typeof AppApiIdRoute
  '/app/aprender/$activityId': typeof AppAprenderActivityIdRoute
  '/app/banco/$id': typeof AppBancoIdRoute
  '/app/blueprint/$id': typeof AppBlueprintIdRoute
  '/app/roadmap/$id': typeof AppRoadmapIdRoute
  '/app/seguranca/$id': typeof AppSegurancaIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/apis': typeof ApiApisRoute
  '/api/assinatura': typeof ApiAssinaturaRoute
  '/api/banco': typeof ApiBancoRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/etapa': typeof ApiEtapaRoute
  '/api/licao': typeof ApiLicaoRoute
  '/api/pratica': typeof ApiPraticaRoute
  '/api/rota': typeof ApiRotaRoute
  '/api/seguranca': typeof ApiSegurancaRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/app/blueprints': typeof AppBlueprintsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/habilidades': typeof AppHabilidadesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/revisar': typeof AppRevisarRoute
  '/app/rota': typeof AppRotaRoute
  '/app': typeof AppIndexRoute
  '/app/api/$id': typeof AppApiIdRoute
  '/app/aprender/$activityId': typeof AppAprenderActivityIdRoute
  '/app/banco/$id': typeof AppBancoIdRoute
  '/app/blueprint/$id': typeof AppBlueprintIdRoute
  '/app/roadmap/$id': typeof AppRoadmapIdRoute
  '/app/seguranca/$id': typeof AppSegurancaIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/apis': typeof ApiApisRoute
  '/api/assinatura': typeof ApiAssinaturaRoute
  '/api/banco': typeof ApiBancoRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/etapa': typeof ApiEtapaRoute
  '/api/licao': typeof ApiLicaoRoute
  '/api/pratica': typeof ApiPraticaRoute
  '/api/rota': typeof ApiRotaRoute
  '/api/seguranca': typeof ApiSegurancaRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/app/blueprints': typeof AppBlueprintsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/habilidades': typeof AppHabilidadesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/planos': typeof AppPlanosRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/revisar': typeof AppRevisarRoute
  '/app/rota': typeof AppRotaRoute
  '/app/': typeof AppIndexRoute
  '/app/api/$id': typeof AppApiIdRoute
  '/app/aprender/$activityId': typeof AppAprenderActivityIdRoute
  '/app/banco/$id': typeof AppBancoIdRoute
  '/app/blueprint/$id': typeof AppBlueprintIdRoute
  '/app/roadmap/$id': typeof AppRoadmapIdRoute
  '/app/seguranca/$id': typeof AppSegurancaIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/.well-known/oauth-protected-resource'
    | '/api/apis'
    | '/api/assinatura'
    | '/api/banco'
    | '/api/blueprint'
    | '/api/etapa'
    | '/api/licao'
    | '/api/pratica'
    | '/api/rota'
    | '/api/seguranca'
    | '/api/stripe-webhook'
    | '/app/blueprints'
    | '/app/configuracoes'
    | '/app/habilidades'
    | '/app/oportunidades'
    | '/app/perfil'
    | '/app/planos'
    | '/app/projetos'
    | '/app/revisar'
    | '/app/rota'
    | '/app/'
    | '/app/api/$id'
    | '/app/aprender/$activityId'
    | '/app/banco/$id'
    | '/app/blueprint/$id'
    | '/app/roadmap/$id'
    | '/app/seguranca/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/.well-known/oauth-protected-resource'
    | '/api/apis'
    | '/api/assinatura'
    | '/api/banco'
    | '/api/blueprint'
    | '/api/etapa'
    | '/api/licao'
    | '/api/pratica'
    | '/api/rota'
    | '/api/seguranca'
    | '/api/stripe-webhook'
    | '/app/blueprints'
    | '/app/configuracoes'
    | '/app/habilidades'
    | '/app/oportunidades'
    | '/app/perfil'
    | '/app/planos'
    | '/app/projetos'
    | '/app/revisar'
    | '/app/rota'
    | '/app'
    | '/app/api/$id'
    | '/app/aprender/$activityId'
    | '/app/banco/$id'
    | '/app/blueprint/$id'
    | '/app/roadmap/$id'
    | '/app/seguranca/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/.well-known/oauth-protected-resource'
    | '/api/apis'
    | '/api/assinatura'
    | '/api/banco'
    | '/api/blueprint'
    | '/api/etapa'
    | '/api/licao'
    | '/api/pratica'
    | '/api/rota'
    | '/api/seguranca'
    | '/api/stripe-webhook'
    | '/app/blueprints'
    | '/app/configuracoes'
    | '/app/habilidades'
    | '/app/oportunidades'
    | '/app/perfil'
    | '/app/planos'
    | '/app/projetos'
    | '/app/revisar'
    | '/app/rota'
    | '/app/'
    | '/app/api/$id'
    | '/app/aprender/$activityId'
    | '/app/banco/$id'
    | '/app/blueprint/$id'
    | '/app/roadmap/$id'
    | '/app/seguranca/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiApisRoute: typeof ApiApisRoute
  ApiAssinaturaRoute: typeof ApiAssinaturaRoute
  ApiBancoRoute: typeof ApiBancoRoute
  ApiBlueprintRoute: typeof ApiBlueprintRoute
  ApiEtapaRoute: typeof ApiEtapaRoute
  ApiLicaoRoute: typeof ApiLicaoRoute
  ApiPraticaRoute: typeof ApiPraticaRoute
  ApiRotaRoute: typeof ApiRotaRoute
  ApiSegurancaRoute: typeof ApiSegurancaRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apis': {
      id: '/api/apis'
      path: '/api/apis'
      fullPath: '/api/apis'
      preLoaderRoute: typeof ApiApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assinatura': {
      id: '/api/assinatura'
      path: '/api/assinatura'
      fullPath: '/api/assinatura'
      preLoaderRoute: typeof ApiAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/banco': {
      id: '/api/banco'
      path: '/api/banco'
      fullPath: '/api/banco'
      preLoaderRoute: typeof ApiBancoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint': {
      id: '/api/blueprint'
      path: '/api/blueprint'
      fullPath: '/api/blueprint'
      preLoaderRoute: typeof ApiBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/etapa': {
      id: '/api/etapa'
      path: '/api/etapa'
      fullPath: '/api/etapa'
      preLoaderRoute: typeof ApiEtapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/licao': {
      id: '/api/licao'
      path: '/api/licao'
      fullPath: '/api/licao'
      preLoaderRoute: typeof ApiLicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pratica': {
      id: '/api/pratica'
      path: '/api/pratica'
      fullPath: '/api/pratica'
      preLoaderRoute: typeof ApiPraticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rota': {
      id: '/api/rota'
      path: '/api/rota'
      fullPath: '/api/rota'
      preLoaderRoute: typeof ApiRotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seguranca': {
      id: '/api/seguranca'
      path: '/api/seguranca'
      fullPath: '/api/seguranca'
      preLoaderRoute: typeof ApiSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blueprints': {
      id: '/app/blueprints'
      path: '/blueprints'
      fullPath: '/app/blueprints'
      preLoaderRoute: typeof AppBlueprintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/habilidades': {
      id: '/app/habilidades'
      path: '/habilidades'
      fullPath: '/app/habilidades'
      preLoaderRoute: typeof AppHabilidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades': {
      id: '/app/oportunidades'
      path: '/oportunidades'
      fullPath: '/app/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planos': {
      id: '/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/revisar': {
      id: '/app/revisar'
      path: '/revisar'
      fullPath: '/app/revisar'
      preLoaderRoute: typeof AppRevisarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rota': {
      id: '/app/rota'
      path: '/rota'
      fullPath: '/app/rota'
      preLoaderRoute: typeof AppRotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api/$id': {
      id: '/app/api/$id'
      path: '/api/$id'
      fullPath: '/app/api/$id'
      preLoaderRoute: typeof AppApiIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprender/$activityId': {
      id: '/app/aprender/$activityId'
      path: '/aprender/$activityId'
      fullPath: '/app/aprender/$activityId'
      preLoaderRoute: typeof AppAprenderActivityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/banco/$id': {
      id: '/app/banco/$id'
      path: '/banco/$id'
      fullPath: '/app/banco/$id'
      preLoaderRoute: typeof AppBancoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blueprint/$id': {
      id: '/app/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/app/blueprint/$id'
      preLoaderRoute: typeof AppBlueprintIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap/$id': {
      id: '/app/roadmap/$id'
      path: '/roadmap/$id'
      fullPath: '/app/roadmap/$id'
      preLoaderRoute: typeof AppRoadmapIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguranca/$id': {
      id: '/app/seguranca/$id'
      path: '/seguranca/$id'
      fullPath: '/app/seguranca/$id'
      preLoaderRoute: typeof AppSegurancaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBlueprintsRoute: typeof AppBlueprintsRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppHabilidadesRoute: typeof AppHabilidadesRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppRevisarRoute: typeof AppRevisarRoute
  AppRotaRoute: typeof AppRotaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppApiIdRoute: typeof AppApiIdRoute
  AppAprenderActivityIdRoute: typeof AppAprenderActivityIdRoute
  AppBancoIdRoute: typeof AppBancoIdRoute
  AppBlueprintIdRoute: typeof AppBlueprintIdRoute
  AppRoadmapIdRoute: typeof AppRoadmapIdRoute
  AppSegurancaIdRoute: typeof AppSegurancaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBlueprintsRoute: AppBlueprintsRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppHabilidadesRoute: AppHabilidadesRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppRevisarRoute: AppRevisarRoute,
  AppRotaRoute: AppRotaRoute,
  AppIndexRoute: AppIndexRoute,
  AppApiIdRoute: AppApiIdRoute,
  AppAprenderActivityIdRoute: AppAprenderActivityIdRoute,
  AppBancoIdRoute: AppBancoIdRoute,
  AppBlueprintIdRoute: AppBlueprintIdRoute,
  AppRoadmapIdRoute: AppRoadmapIdRoute,
  AppSegurancaIdRoute: AppSegurancaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiApisRoute: ApiApisRoute,
  ApiAssinaturaRoute: ApiAssinaturaRoute,
  ApiBancoRoute: ApiBancoRoute,
  ApiBlueprintRoute: ApiBlueprintRoute,
  ApiEtapaRoute: ApiEtapaRoute,
  ApiLicaoRoute: ApiLicaoRoute,
  ApiPraticaRoute: ApiPraticaRoute,
  ApiRotaRoute: ApiRotaRoute,
  ApiSegurancaRoute: ApiSegurancaRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
